//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBooks
    {
        public int Id { get; set; }
        public string UserNo { get; set; }
        public string CodeNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EngName { get; set; }
        public string GenderCode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string CompName { get; set; }
        public string CompID { get; set; }
        public string DeptName { get; set; }
        public string TitleName { get; set; }
        public string CompTel { get; set; }
        public string ContactTel { get; set; }
        public string ContactEmail { get; set; }
        public string ContactAddress { get; set; }
        public string LineID { get; set; }
        public string FacebookID { get; set; }
        public string TwitterID { get; set; }
        public string InstagramID { get; set; }
        public string LinkedInID { get; set; }
        public string Remark { get; set; }
    }
}
