//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendars
    {
        public int Id { get; set; }
        public string TargetCode { get; set; }
        public string TargetNo { get; set; }
        public string CodeNo { get; set; }
        public string SubjectName { get; set; }
        public System.DateTime StartDate { get; set; }
        public string StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public string EndTime { get; set; }
        public string ColorName { get; set; }
        public bool IsFullday { get; set; }
        public string PlaceName { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string PlaceAddress { get; set; }
        public string RoomNo { get; set; }
        public string ResourceText { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
    }
}
