//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<AboutUsDetails> AboutUsDetails { get; set; }
        public virtual DbSet<AddressBooks> AddressBooks { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<BookingRecord> BookingRecord { get; set; }
        public virtual DbSet<Calendars> Calendars { get; set; }
        public virtual DbSet<Carousels> Carousels { get; set; }
        public virtual DbSet<Categorys> Categorys { get; set; }
        public virtual DbSet<CinemaHall> CinemaHall { get; set; }
        public virtual DbSet<CityAreas> CityAreas { get; set; }
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<CloseDates> CloseDates { get; set; }
        public virtual DbSet<CodeBases> CodeBases { get; set; }
        public virtual DbSet<CodeDatas> CodeDatas { get; set; }
        public virtual DbSet<Companys> Companys { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<ExtensionTables> ExtensionTables { get; set; }
        public virtual DbSet<Featureds> Featureds { get; set; }
        public virtual DbSet<FormDetail> FormDetail { get; set; }
        public virtual DbSet<FormMaster> FormMaster { get; set; }
        public virtual DbSet<ForumBoards> ForumBoards { get; set; }
        public virtual DbSet<Forums> Forums { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<MapPositions> MapPositions { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsLetter> NewsLetter { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersStatus> OrdersStatus { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<PricingDetails> PricingDetails { get; set; }
        public virtual DbSet<Pricings> Pricings { get; set; }
        public virtual DbSet<ProductFeatureds> ProductFeatureds { get; set; }
        public virtual DbSet<ProductInventorys> ProductInventorys { get; set; }
        public virtual DbSet<ProductPropertys> ProductPropertys { get; set; }
        public virtual DbSet<ProductRelations> ProductRelations { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Programs> Programs { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
        public virtual DbSet<PropertyNames> PropertyNames { get; set; }
        public virtual DbSet<Propertys> Propertys { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Securitys> Securitys { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Shippings> Shippings { get; set; }
        public virtual DbSet<Shows> Shows { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
        public virtual DbSet<TodoLists> TodoLists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
        public virtual DbSet<WorkflowDetails> WorkflowDetails { get; set; }
        public virtual DbSet<WorkflowMasters> WorkflowMasters { get; set; }
        public virtual DbSet<WorkflowRoles> WorkflowRoles { get; set; }
        public virtual DbSet<WorkflowRoleUsers> WorkflowRoleUsers { get; set; }
        public virtual DbSet<WorkflowRoutes> WorkflowRoutes { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
    }
}
