//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Id { get; set; }
        public bool IsValid { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string GenderCode { get; set; }
        public string DeptNo { get; set; }
        public string TitleNo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> OnboardDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string ContactEmail { get; set; }
        public string ContactTel { get; set; }
        public string ContactAddress { get; set; }
        public string Remark { get; set; }
    }
}
