//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieId { get; set; }
        public string MovieNo { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Duration { get; set; }
        public string pic { get; set; }
    }
}
