//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string SheetNo { get; set; }
        public System.DateTime SheetDate { get; set; }
        public string StatusCode { get; set; }
        public bool IsClosed { get; set; }
        public bool IsValid { get; set; }
        public string CustNo { get; set; }
        public string CustName { get; set; }
        public string PaymentNo { get; set; }
        public string ShippingNo { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverEmail { get; set; }
        public string ReceiverAddress { get; set; }
        public int OrderAmount { get; set; }
        public int TaxAmount { get; set; }
        public int TotalAmount { get; set; }
        public string Remark { get; set; }
        public string GuidNo { get; set; }
    }
}
