//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricings
    {
        public int Id { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsAdvanced { get; set; }
        public bool IsRecommend { get; set; }
        public string SortNo { get; set; }
        public string PricingNo { get; set; }
        public string PricingName { get; set; }
        public int ProdPrice { get; set; }
        public string CycleName { get; set; }
        public string Remark { get; set; }
    }
}
