//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public int Id { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsPageSize { get; set; }
        public bool IsSearch { get; set; }
        public string RoleNo { get; set; }
        public string ModuleNo { get; set; }
        public string SortNo { get; set; }
        public string PrgNo { get; set; }
        public string PrgName { get; set; }
        public string CodeNo { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ParmValue { get; set; }
        public int PageSize { get; set; }
        public string Remark { get; set; }
    }
}
