//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int Id { get; set; }
        public string SortNo { get; set; }
        public string TeamNo { get; set; }
        public string TeamName { get; set; }
        public string EngName { get; set; }
        public string GenderCode { get; set; }
        public string DeptName { get; set; }
        public string TitleName { get; set; }
        public string TwitterUrl { get; set; }
        public string FacebookUrl { get; set; }
        public string LinkedinUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string SkypeUrl { get; set; }
        public string ContactEmail { get; set; }
        public string DetailText { get; set; }
        public string Remark { get; set; }
    }
}
