//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ETicket.Resources
{
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resCommon
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resCommon()
        {
        }

        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETicket.Resources.resCommon", typeof(resCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查詢類似 帳戶 的當地語系化字串。
        /// </summary>
        public static string Account
        {
            get
            {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 帳號性別 的當地語系化字串。
        /// </summary>
        public static string AccountGender
        {
            get
            {
                return ResourceManager.GetString("AccountGender", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 帳號名稱 的當地語系化字串。
        /// </summary>
        public static string AccountName
        {
            get
            {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 登入帳號 的當地語系化字串。
        /// </summary>
        public static string AccountNo
        {
            get
            {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 通訊錄 的當地語系化字串。
        /// </summary>
        public static string AddressBook
        {
            get
            {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 全天 的當地語系化字串。
        /// </summary>
        public static string AllDay
        {
            get
            {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 行事曆 的當地語系化字串。
        /// </summary>
        public static string Calendar
        {
            get
            {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 分類 的當地語系化字串。
        /// </summary>
        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 關閉視窗 的當地語系化字串。
        /// </summary>
        public static string CloseWindow
        {
            get
            {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 公司 的當地語系化字串。
        /// </summary>
        public static string Company
        {
            get
            {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 公司名稱 的當地語系化字串。
        /// </summary>
        public static string CompanyName
        {
            get
            {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 連絡地址 的當地語系化字串。
        /// </summary>
        public static string ContactAddress
        {
            get
            {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 連絡人 的當地語系化字串。
        /// </summary>
        public static string Contactor
        {
            get
            {
                return ResourceManager.GetString("Contactor", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 連絡電話 的當地語系化字串。
        /// </summary>
        public static string ContactPhone
        {
            get
            {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        public static string Copy
        {
            get
            {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 建立日期 的當地語系化字串。
        /// </summary>
        public static string CreateDate
        {
            get
            {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 建立時間 的當地語系化字串。
        /// </summary>
        public static string CreateTime
        {
            get
            {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 目前 的當地語系化字串。
        /// </summary>
        public static string Current
        {
            get
            {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 目前位置 的當地語系化字串。
        /// </summary>
        public static string CurrentPosition
        {
            get
            {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 客戶 的當地語系化字串。
        /// </summary>
        public static string Customer
        {
            get
            {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 日期 的當地語系化字串。
        /// </summary>
        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 部門名稱 的當地語系化字串。
        /// </summary>
        public static string DepartmentName
        {
            get
            {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 說明 的當地語系化字串。
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        public static string Detail
        {
            get
            {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 元 的當地語系化字串。
        /// </summary>
        public static string Dollar
        {
            get
            {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        public static string Download
        {
            get
            {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 修改資料 的當地語系化字串。
        /// </summary>
        public static string EditData
        {
            get
            {
                return ResourceManager.GetString("EditData", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 電子信箱 的當地語系化字串。
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 員工 的當地語系化字串。
        /// </summary>
        public static string Employee
        {
            get
            {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 結束 的當地語系化字串。
        /// </summary>
        public static string End
        {
            get
            {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 結束日期 的當地語系化字串。
        /// </summary>
        public static string EndDate
        {
            get
            {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        public static string EndTime
        {
            get
            {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 英文名 的當地語系化字串。
        /// </summary>
        public static string EnglishName
        {
            get
            {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 預定完成日 的當地語系化字串。
        /// </summary>
        public static string EstimatedDate
        {
            get
            {
                return ResourceManager.GetString("EstimatedDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 行程 的當地語系化字串。
        /// </summary>
        public static string Event
        {
            get
            {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 檔案 的當地語系化字串。
        /// </summary>
        public static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string Find
        {
            get
            {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 完成 的當地語系化字串。
        /// </summary>
        public static string Finish
        {
            get
            {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 全名 的當地語系化字串。
        /// </summary>
        public static string FullName
        {
            get
            {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 全螢幕 的當地語系化字串。
        /// </summary>
        public static string FullScreen
        {
            get
            {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        public static string Gender
        {
            get
            {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 標題 的當地語系化字串。
        /// </summary>
        public static string Header
        {
            get
            {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 圖片 的當地語系化字串。
        /// </summary>
        public static string Image
        {
            get
            {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 圖庫 的當地語系化字串。
        /// </summary>
        public static string Images
        {
            get
            {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 列表 的當地語系化字串。
        /// </summary>
        public static string Index
        {
            get
            {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 項目 的當地語系化字串。
        /// </summary>
        public static string Item
        {
            get
            {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 語系 的當地語系化字串。
        /// </summary>
        public static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 資料列表 的當地語系化字串。
        /// </summary>
        public static string List
        {
            get
            {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 地圖 的當地語系化字串。
        /// </summary>
        public static string Map
        {
            get
            {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 材料 的當地語系化字串。
        /// </summary>
        public static string Material
        {
            get
            {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 會議 的當地語系化字串。
        /// </summary>
        public static string Meeting
        {
            get
            {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 會議室 的當地語系化字串。
        /// </summary>
        public static string MeetingRoom
        {
            get
            {
                return ResourceManager.GetString("MeetingRoom", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 會員 的當地語系化字串。
        /// </summary>
        public static string Member
        {
            get
            {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 管理者 的當地語系化字串。
        /// </summary>
        public static string Mis
        {
            get
            {
                return ResourceManager.GetString("Mis", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 更多 的當地語系化字串。
        /// </summary>
        public static string More
        {
            get
            {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 我的帳戶 的當地語系化字串。
        /// </summary>
        public static string MyAccount
        {
            get
            {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 最新消息 的當地語系化字串。
        /// </summary>
        public static string News
        {
            get
            {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 編號 的當地語系化字串。
        /// </summary>
        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 到職日期 的當地語系化字串。
        /// </summary>
        public static string OnboardDate
        {
            get
            {
                return ResourceManager.GetString("OnboardDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 頁總數 的當地語系化字串。
        /// </summary>
        public static string PageCount
        {
            get
            {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 頁數 的當地語系化字串。
        /// </summary>
        public static string PageNumber
        {
            get
            {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 人 的當地語系化字串。
        /// </summary>
        public static string Person
        {
            get
            {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 個人 的當地語系化字串。
        /// </summary>
        public static string Personal
        {
            get
            {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 個人化 的當地語系化字串。
        /// </summary>
        public static string Personalize
        {
            get
            {
                return ResourceManager.GetString("Personalize", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 件 的當地語系化字串。
        /// </summary>
        public static string Piece
        {
            get
            {
                return ResourceManager.GetString("Piece", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 地點 的當地語系化字串。
        /// </summary>
        public static string Place
        {
            get
            {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 請輸入內容!! 的當地語系化字串。
        /// </summary>
        public static string PlaceHolder
        {
            get
            {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 位置 的當地語系化字串。
        /// </summary>
        public static string Position
        {
            get
            {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        public static string Print
        {
            get
            {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商品 的當地語系化字串。
        /// </summary>
        public static string Product
        {
            get
            {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 規格 的當地語系化字串。
        /// </summary>
        public static string Property
        {
            get
            {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string Remark
        {
            get
            {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 重設密碼 的當地語系化字串。
        /// </summary>
        public static string ResetPassword
        {
            get
            {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 資源 的當地語系化字串。
        /// </summary>
        public static string Resource
        {
            get
            {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 返回 的當地語系化字串。
        /// </summary>
        public static string Return
        {
            get
            {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 返回首頁 的當地語系化字串。
        /// </summary>
        public static string ReturnHome
        {
            get
            {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 返回列表 的當地語系化字串。
        /// </summary>
        public static string ReturnIndex
        {
            get
            {
                return ResourceManager.GetString("ReturnIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 返回資料列表 的當地語系化字串。
        /// </summary>
        public static string ReturnList
        {
            get
            {
                return ResourceManager.GetString("ReturnList", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 房間 的當地語系化字串。
        /// </summary>
        public static string Room
        {
            get
            {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 存檔 的當地語系化字串。
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商城 的當地語系化字串。
        /// </summary>
        public static string Shop
        {
            get
            {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 購物商城 的當地語系化字串。
        /// </summary>
        public static string ShoppingMall
        {
            get
            {
                return ResourceManager.GetString("ShoppingMall", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 大小 的當地語系化字串。
        /// </summary>
        public static string Size
        {
            get
            {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string Sort
        {
            get
            {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 規格 的當地語系化字串。
        /// </summary>
        public static string Specification
        {
            get
            {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 開始 的當地語系化字串。
        /// </summary>
        public static string Start
        {
            get
            {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 開始日期 的當地語系化字串。
        /// </summary>
        public static string StartDate
        {
            get
            {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 開始時間 的當地語系化字串。
        /// </summary>
        public static string StartTime
        {
            get
            {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string Telphone
        {
            get
            {
                return ResourceManager.GetString("Telphone", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 時間 的當地語系化字串。
        /// </summary>
        public static string Time
        {
            get
            {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 次 的當地語系化字串。
        /// </summary>
        public static string Times
        {
            get
            {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 職務名稱 的當地語系化字串。
        /// </summary>
        public static string TitleName
        {
            get
            {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 工作清單 的當地語系化字串。
        /// </summary>
        public static string TodoList
        {
            get
            {
                return ResourceManager.GetString("TodoList", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        public static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 類別名稱 的當地語系化字串。
        /// </summary>
        public static string TypeName
        {
            get
            {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 未定義 的當地語系化字串。
        /// </summary>
        public static string UnDefind
        {
            get
            {
                return ResourceManager.GetString("UnDefind", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 更新 的當地語系化字串。
        /// </summary>
        public static string Update
        {
            get
            {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 上傳 的當地語系化字串。
        /// </summary>
        public static string Upload
        {
            get
            {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 上傳檔案 的當地語系化字串。
        /// </summary>
        public static string UploadFile
        {
            get
            {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 上傳圖片 的當地語系化字串。
        /// </summary>
        public static string UploadImage
        {
            get
            {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 上傳圖庫 的當地語系化字串。
        /// </summary>
        public static string UploadImages
        {
            get
            {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 廠商 的當地語系化字串。
        /// </summary>
        public static string Vendor
        {
            get
            {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 版本 的當地語系化字串。
        /// </summary>
        public static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
