//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ETicket.Resources
{
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resColumn
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resColumn()
        {
        }

        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETicket.Resources.resColumn", typeof(resColumn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查詢類似 發佈時間 的當地語系化字串。
        /// </summary>
        public static string date_publish
        {
            get
            {
                return ResourceManager.GetString("date_publish", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 第一個 的當地語系化字串。
        /// </summary>
        public static string is_active
        {
            get
            {
                return ResourceManager.GetString("is_active", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 標題 的當地語系化字串。
        /// </summary>
        public static string name_header
        {
            get
            {
                return ResourceManager.GetString("name_header", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string no_sort
        {
            get
            {
                return ResourceManager.GetString("no_sort", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string remark
        {
            get
            {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 次要標題 的當地語系化字串。
        /// </summary>
        public static string text_descript
        {
            get
            {
                return ResourceManager.GetString("text_descript", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 詳細內文 的當地語系化字串。
        /// </summary>
        public static string text_detail
        {
            get
            {
                return ResourceManager.GetString("text_detail", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 分類名稱 的當地語系化字串。
        /// </summary>
        public static string type_name
        {
            get
            {
                return ResourceManager.GetString("type_name", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 分類編號 的當地語系化字串。
        /// </summary>
        public static string type_no
        {
            get
            {
                return ResourceManager.GetString("type_no", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 圖片網址 的當地語系化字串。
        /// </summary>
        public static string url_image
        {
            get
            {
                return ResourceManager.GetString("url_image", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 更多網址 的當地語系化字串。
        /// </summary>
        public static string url_more
        {
            get
            {
                return ResourceManager.GetString("url_more", resourceCulture);
            }
        }
    }
}
