//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ETicket.Resources
{
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resProgram
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resProgram()
        {
        }

        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETicket.Resources.resProgram", typeof(resProgram).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查詢類似 基本資料 的當地語系化字串。
        /// </summary>
        public static string BAS
        {
            get
            {
                return ResourceManager.GetString("BAS", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商品基本資料 的當地語系化字串。
        /// </summary>
        public static string BASP001
        {
            get
            {
                return ResourceManager.GetString("BASP001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 部門基本資料 的當地語系化字串。
        /// </summary>
        public static string BASP002
        {
            get
            {
                return ResourceManager.GetString("BASP002", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 職稱基本資料 的當地語系化字串。
        /// </summary>
        public static string BASP003
        {
            get
            {
                return ResourceManager.GetString("BASP003", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單狀態資料 的當地語系化字串。
        /// </summary>
        public static string BASP004
        {
            get
            {
                return ResourceManager.GetString("BASP004", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商品屬性維護 的當地語系化字串。
        /// </summary>
        public static string BASP005
        {
            get
            {
                return ResourceManager.GetString("BASP005", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商品類別維護 的當地語系化字串。
        /// </summary>
        public static string BASP006
        {
            get
            {
                return ResourceManager.GetString("BASP006", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商品分類維護 的當地語系化字串。
        /// </summary>
        public static string BASP007
        {
            get
            {
                return ResourceManager.GetString("BASP007", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 商品基本資料表 的當地語系化字串。
        /// </summary>
        public static string BASR001
        {
            get
            {
                return ResourceManager.GetString("BASR001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單模組 的當地語系化字串。
        /// </summary>
        public static string ODR
        {
            get
            {
                return ResourceManager.GetString("ODR", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 未結訂單查詢 的當地語系化字串。
        /// </summary>
        public static string ODRP001
        {
            get
            {
                return ResourceManager.GetString("ODRP001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 已結訂單查詢 的當地語系化字串。
        /// </summary>
        public static string ODRP002
        {
            get
            {
                return ResourceManager.GetString("ODRP002", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單模組 的當地語系化字串。
        /// </summary>
        public static string ORD
        {
            get
            {
                return ResourceManager.GetString("ORD", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 未結訂單管理 的當地語系化字串。
        /// </summary>
        public static string ORDP001
        {
            get
            {
                return ResourceManager.GetString("ORDP001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 已結訂單查詢 的當地語系化字串。
        /// </summary>
        public static string ORDP002
        {
            get
            {
                return ResourceManager.GetString("ORDP002", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單明細表 的當地語系化字串。
        /// </summary>
        public static string ORDR001
        {
            get
            {
                return ResourceManager.GetString("ORDR001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 組織模組 的當地語系化字串。
        /// </summary>
        public static string ORG
        {
            get
            {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 公司資料維護 的當地語系化字串。
        /// </summary>
        public static string ORGP001
        {
            get
            {
                return ResourceManager.GetString("ORGP001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 使用者資料維護 的當地語系化字串。
        /// </summary>
        public static string ORGP002
        {
            get
            {
                return ResourceManager.GetString("ORGP002", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單模組 的當地語系化字串。
        /// </summary>
        public static string ORM
        {
            get
            {
                return ResourceManager.GetString("ORM", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單管理 的當地語系化字串。
        /// </summary>
        public static string ORMP001
        {
            get
            {
                return ResourceManager.GetString("ORMP001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 訂單狀態維護 的當地語系化字串。
        /// </summary>
        public static string ORMS001
        {
            get
            {
                return ResourceManager.GetString("ORMS001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 程式模組 的當地語系化字串。
        /// </summary>
        public static string PRG
        {
            get
            {
                return ResourceManager.GetString("PRG", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 模組資料維護 的當地語系化字串。
        /// </summary>
        public static string PRGP001
        {
            get
            {
                return ResourceManager.GetString("PRGP001", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 程式資料維護 的當地語系化字串。
        /// </summary>
        public static string PRGP002
        {
            get
            {
                return ResourceManager.GetString("PRGP002", resourceCulture);
            }
        }
    }
}
